### ISSUE TITLE
HTTP to HTTPS redirect mix-ups virtual hosts.

### ISSUE THREAD

**Issue by markandpathak** [digitalocean/nginxconfig.io#169] opened 2020-09-23 17:11 UTC
Thanks for this amazing tool!

The issue is as following:
If there are two virtual hosts (Server blocks) serving two host names or subdomains:
```
sd1.domain.com
sd2.domain.com
```
When the configuration is generated using the nginxconfig and if HTTP to HTTPS redirect is enabled following server block gets generated for each host:
```
--- For virtual host 1
# HTTP redirect
server {
    listen 80;
    listen [::]:80;
    return 301 https://sd1.domain.com$request_uri;
}

-- For virtual host 2
# HTTP redirect
server {
    listen 80;
    listen [::]:80;
    return 301 https://sd2.domain.com$request_uri;
}
```
Now when both sites are enabled, and if any request is received over HTTP, the server block which was included in main config file first will be considered, which may result in redirect to a different virtual host over HTTPS. This issue can be easily reproduced.

For example: If request is for `http://sd2.domain.com` but first redirect server block read by the nginx from config is for sd1.domain.com, then request will be redirected to `https://sd1.domain.com` as server block does not contain any server_name to distinguish incoming request. 

There are two ways in which this issue can be solved:
Either include only one redirect block which redirects to appropriate host:
```
server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
```
Or include independent redirect block with server_name:
```
server {
    listen 80;
    server_name sd1.domain.com;
    return 301 https://sd1.domain.com$request_uri;
}
```
Attribution: The solution was referred from [https://serversforhackers.com/c/redirect-http-to-https-nginx](url)

**Comment by MattIPv4** [comment] 2020-09-23 22:41
👍 Good catch. I think the latter option of adding the `server_name mydomain.com` is the better option here.

**Comment by RytoEX** [comment] 2020-10-04 08:32
When I [attempted to reproduce](https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=sd1.example.com&domains.0.server.redirectSubdomains=false&domains.1.server.domain=sd2.example.com&domains.1.server.redirectSubdomains=false) this, the server blocks ended up with the seemingly appropriate `server_name` items.  This seems like it is a duplicate of #160, though I'm not sure how since that was closed in July.  Perhaps I misunderstood something?

**Comment by markandpathak** [comment] 2020-10-15 06:02
@RytoEX Indeed the issue is identical to #160, for which I think appropriate code is implemented but it is not reflected in hosted version on Digitalocean. Strangely though, the configuration link you shared has HTTP to HTTPS redirect section completely missing from both virtual hosts (See image). There is just a comment `# HTTP redirect`. I confirmed it by downloading the config archive also.

@MattIPv4 Here is the link [link](https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=console.invesun.com&domains.0.server.path=%2Fvar%2Fwww%2Finvesun-frontend&domains.0.server.documentRoot=%2F&domains.0.server.redirectSubdomains=false&domains.0.https.certType=custom&domains.0.https.sslCertificate=%2Fetc%2Fletsencrypt%2Flive%2Finvesun.com%2Ffullchain.pem&domains.0.https.sslCertificateKey=%2Fetc%2Fletsencrypt%2Flive%2Finvesun.com%2Fprivkey.pem&domains.0.php.php=false&domains.0.routing.index=index.html&domains.0.routing.fallbackHtml=true&domains.0.routing.fallbackPhp=false&domains.1.server.domain=api.invesun.com&domains.1.server.redirectSubdomains=false&domains.1.https.certType=custom&domains.1.https.sslCertificate=%2Fetc%2Fletsencrypt%2Flive%2Finvesun.com%2Ffullchain.pem&domains.1.https.sslCertificateKey=%2Fetc%2Fletsencrypt%2Flive%2Finvesun.com%2Fprivkey.pem&domains.1.php.php=false&domains.1.reverseProxy.reverseProxy=true&domains.1.reverseProxy.proxyPass=http%3A%2F%2F127.0.0.1%3A5000&domains.2.server.domain=do.invesun.com&domains.2.server.redirectSubdomains=false&domains.2.https.certType=custom&domains.2.https.sslCertificate=%2Fetc%2Fletsencrypt%2Flive%2Finvesun.com%2Ffullchain.pem&domains.2.https.sslCertificateKey=%2Fetc%2Fletsencrypt%2Flive%2Finvesun.com%2Fprivkey.pem&domains.2.php.php=false&domains.2.reverseProxy.reverseProxy=true&domains.2.reverseProxy.proxyPass=http%3A%2F%2F127.0.0.1%3A8080). But redirect is missing in this config also. Which wasn't the case when I previously created config. I think the hosted code has been updated after that.
![image](https://user-images.githubusercontent.com/14177294/96081522-0fc10e80-0ed7-11eb-9d68-bbe9d20482d8.png)

**Comment by RytoEX** [comment] 2020-10-15 06:10
The HTTP redirect sections were definitely present and looked proper when I last tested this.

**Comment by RytoEX** [comment] 2020-10-15 06:16
It seems that now the HTTP redirect section only shows up if you enable "Redirect subdomains".  I would guess that something in https://github.com/digitalocean/nginxconfig.io/commit/40aed640340b9b1ab65fa3fb5492c4445a14877c has thrown this off.

**Comment by RytoEX** [comment] 2020-10-15 07:12
I've filed #180 to address the newly discussed issue above.  I did not use a "close" keyword because I think the original issue here has been resolved, and the newly discussed issue is a separate matter.

**Comment by MattIPv4** [comment] 2020-10-15 17:01
Tyvm @RytoEX!

@markandpathak how're things looking now if you force refresh the page to get the latest version of the tool?

**Comment by markandpathak** [comment] 2020-10-16 13:47
Tyvm @RytoEX and @MattIPv4. Everything seems working perfectly now.

**Comment by MattIPv4** [comment] 2020-10-20 19:16
👍 Sweet, will close

**Closed by MattIPv4** 2020-10-20 19:16 UTC
Labels: bug, good first issue, hacktoberfest
