### ISSUE TITLE
gzip: stdin: invalid compressed data--format violated

### ISSUE THREAD

**Issue by softmarshmallow** [digitalocean/nginxconfig.io#154] opened 2020-06-18 17:16 UTC
copie'd with [config](https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=209.97.163.230&domains.0.php.php=false&domains.0.reverseProxy.reverseProxy=true&domains.0.routing.root=false)

when,..
`tar -xzvf nginxconfig.io-209.97.163.230.tar.gz`

throws

```
gzip: stdin: invalid compressed data--format violated
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by MattIPv4** [comment] 2020-06-18 17:32
This is super weird -- I'm unable to reproduce this using the config you linked to when using both the download option as well as the base 64 option.

**Comment by MattIPv4** [comment] 2020-09-28 11:41
CNR, no other reports, closing.

**Closed by MattIPv4** 2020-09-28 11:41 UTC

**Comment by Ghostff** [comment] 2022-08-29 05:51
Came across this issue while using Windows Terminal. Everything worked fine after switching to the dashboard console, and rebuilding the gzip.
